---
- hosts: all

  gather_facts: no
  remote_user: "{{ user }}"
  become: no

  tasks:
    #curl api.ipify.org
    - name: Get my public IP
      register: ip_result
      community.general.ipify_facts:

    - name: Display public ip
      ansible.builtin.debug:
        msg: "{{ ip_result.ansible_facts.ipify_public_ip}}"