---
- hosts: all
  vars:
    user: azureuser
    consul_servers:
      - consul-a
      - consul-b
      - consul-c
    vault_port: 8200
    consul_image_name: my-consul
    consul_build_files_dir: consul-files
    base_consul_dir: ~/consul
    consul_config_dir: "{{ base_consul_dir }}/config"
    consul_container_config_dir: "/etc/consul"

  gather_facts: no
  remote_user: "{{ user }}"
  become: no

  tasks:
    - name: Create new TLS certificates for Vault and Consul
      include_role:
        name: create-tls-certs
      vars:
        is_https: true

    - name: (Re)start consul docker containers
      include_role:
        name: consul-container-restart-all

    - name: (Re)start Vault docker containers
      include_role:
        name: vault-container-restart-all