---
#temp_build_dir should be service specific dir containing files e.g. /tmp/build/consul
#dest_config_dir should be the service specific config dir that config files will be copied to e.g. ~/vault/config (no trailing /)
#dest_build_dir should be the specific build dir for the relevant service e.g. ~/vault-build (no trailing /)
vars:
  my_vault_servers: #use dict so a port number can be specified for each vault server to facilitate running multiple containers on a single host
    vault-a: 8200
    vault-b: 8800

- debug:
    msg: "The base dir is set to {{ base_dir }}. 
          The file is set to {{ consul_servers[0] }}."

- name: Check if the temp build config file exists
  ansible.builtin.stat:
      path: "{{ base_dir }}/consul-files/{{ consul_servers[0] }}.hcl"
  register: temp_file

- name: Fetch the build files from github
  include_role:
    name: fetch-build-files
  when: not temp_file.stat.exists or {{ force_fetch }}
   
- name: Move the consul config files to the persistent/permanent storage location expected by Docker
  include_tasks: move-files.yml
  vars:
    dst_dir: "{{ base_consul_dir }}/{{ item }}/config/"
    src_file: "{{ base_dir }}/{{ consul_build_files_dir }}/{{ item }}.hcl"
    dst_file: "{{ dst_dir }}{{ item }}.hcl"
  loop: "{{ consul_servers }}"
  when: not temp_file.stat.exists or {{ force_fetch }} #since no register possible for include_role assume it succeeded

- name: Move the vault config files to the persistent/permanent storage location expected by Docker
  include_tasks: move-files.yml
  vars:
    dst_dir: "{{ base_vault_dir }}/{{ item.key }}/config/"
    src_file: "{{ base_dir }}/{{ vault_build_files_dir }}/{{ item.key }}.hcl"
    dst_file: "{{ dst_dir }}{{ item.key }}.hcl"
  with_items: "{{ my_vault_servers }}"
  when: not temp_file.stat.exists or {{ force_fetch }} #since no register possible for include_role assume it succeeded

- name: Move the vault consul client config files to the persistent/permanent storage location expected by Docker
  include_tasks: move-files.yml
  vars:
    dst_dir: "{{ base_vault_dir }}/{{ item.key }}/config/"
    src_file: "{{ base_dir }}/{{ vault_build_files_dir }}/{{ item.key }}-consul.hcl"
    dst_file: "{{ dst_dir }}{{ item.key }}-consul.hcl"
  with_items: "{{ my_vault_servers }}"
  when: not temp_file.stat.exists or {{ force_fetch }} #since no register possible for include_role assume it succeeded

  # loop:
  #   - name: consul_dir
  #     source_dir: "{{ base_dir }}/{{ consul_build_files_dir }}"
  #     dest_dir: "{{ consul_config_dir }}"
  #   - name: vault_dir
  #     source_dir: "{{ base_dir }}/{{ vault_build_files_dir }}"
  #     dest_dir: "{{ vault_config_dir }}"
  # loop_control:
  #   loop_var: files_dir


  # - name: Copy temp build files to build dir
  #   copy:
  #     src: "{{ item }}"
  #     dest: "{{ dest_build_dir }}"/ #trailing / means directory will be created where doesnt already exist
  #   with_fileglob:
  #     - "{{ temp_build_dir }}/*"

  # - name: Delete temp build consul directory
  #   file:
  #     state: absent
  #     path: "{{ temp_build_dir }}/"
  # when: dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir