---

#temp_build_dir should be service specific dir containing files e.g. /tmp/build/consul
#dest_config_dir should be the service specific config dir that config files will be copied to e.g. ~/vault/config (no trailing /)
#dest_build_dir should be the specific build dir for the relevant service e.g. ~/vault-build (no trailing /)
- name: Pull down all the required ansible, app config and docker files to build the stack
    ansible.builtin.git:
      repo: 'https://github.com/faster-now/hashi-vault.git'
      dest: "{{ base_dir }}"
      #version: release-0.22

# - name: Check if the temp build directory exists
#     ansible.builtin.stat:
#        path: "{{ temp_build_dir }}"
#     register: dir_to_check
   
- block:
  - name: Copy config files from initial pull down dir to persistant storage location (ready for Docker volume)
    copy:
      src: "{{ item }}"
      dest: "{{ files_dir.dest_dir }}/" #trailing / means directory will be created where doesnt already exist
    with_fileglob:
      - "{{ files_dir.source_dir }}/*.hcl"
  - name: Delete temp config files
    file:
      state: absent
      path: "{{ item }}"
    with_fileglob:
      - "{{ files_dir.source_dir }}/*.hcl"
  loop:
    - name: consul_dir
        source_dir: "{{ base_dir }}/{{ consul_build_files_dir }}"
        dest_dir: "{{ consul_config_dir }}"
    - name: vault_dir 
        source_dir: "{{ base_dir }}/{{ vault_build_files_dir }}"
        dest_dir: "{{ vault_config_dir }}"
  loop_control:
    loop_var: files_dir

  # - name: Copy temp build files to build dir
  #   copy:
  #     src: "{{ item }}"
  #     dest: "{{ dest_build_dir }}"/ #trailing / means directory will be created where doesnt already exist
  #   with_fileglob:
  #     - "{{ temp_build_dir }}/*"

  # - name: Delete temp build consul directory
  #   file:
  #     state: absent
  #     path: "{{ temp_build_dir }}/"
  # when: dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir