---
# - name: Copy config files from initial pull down dir to persistant storage location (ready for Docker volume)
#   copy:
#     src: "{{ item }}"
#     dest: "{{ files_dir.dest_dir }}/" #trailing / means directory will be created where doesnt already exist
#   with_fileglob:
#     - "{{ files_dir.source_dir }}/*.hcl"

# - name: Delete temp config files
#   file:
#     state: absent
#     path: "{{ item }}"
#   with_fileglob:
#     - "{{ files_dir.source_dir }}/*.hcl"

- name: Create persistent storage directory
  file:
    state: directory
    path: "{{ dst_file | dirname }}"

- debug:
    msg: "The destination dir is set to {{ dst_file | dirname }}.\nThe source file is set to {{ src_file }}.\nThe dest file is set to {{ dst_file }}."

- name: Copy config files from initial pull down dir to persistant storage location (ready for Docker volume)
  copy:
    src: "{{ src_file }}"
    dest: "{{ dst_file }}"

- name: Delete temp config files
  file:
    state: absent
    path: "{{ src_file }}"

    #consul/consul-a/config