---

- name: Create TLS certificate
  community.hashi_vault.vault_write:
    url: "{{ vault_url }}"
    path: pki_int/issue/leaf_certs
    data:
      common_name: "{{ cname }}"
      alt_names: "{{ alt_names }}"
      ttl: "{{ cert_lifetime }}"
    token: "{{ vault_token }}"
    token_validate: false
  register: certs_and_keys

- name: Write Vault TLS certificate with issung CA cert appended
  copy:
    content: | 
      {{ certs_and_keys.data.data.certificate }}
      {{ certs_and_keys.data.data.issuing_ca }}
    dest: "{{ cert_file }}"

- name: Write TLS private key to file
  copy:
    content: "{{ certs_and_keys.data.data.private_key }}"
    dest: "{{ key_file }}"

- name: Write ca cert to file
  copy:
    content: "{{ certs_and_keys.data.data.issuing_ca }}"
    dest: "{{ ca_file }}"

# - name: Add new encryption key to config
#   lineinfile:
#     path: "~/consul/{{ item }}.hcl" #Add to all config files
#     regexp: "^encrypt\s*=\s*"
#     line: "encrypt = \"{{ consul_enc_key }}\" #generated by Ansible"
#   notify: Restart Consul #even though in a loop, will only result in one restart
#   when:
#     - consul_enc_key is defined
#   loop: "{{consul_servers}}"

# handlers:
#   - name: Restart Consul
#       docker_container:
#         name: "{{ item }}"
#         image: "{{consul_image_name}}:v1"
#         state: started
#         restart_policy: unless-stopped
#         restart: yes
#         networks:
#           - name: "{{ docker_network }}"
#         volumes:
#           - "~/consul/{{item}}.hcl:/etc/consul/consul.hcl"
#           - "~/consul-storage/{{item}}/:/opt/consul-storage"
#       loop: "{{consul_servers}}"

#TODO update config files then restart containers
