---
- name: Check if vault is using TLS
  uri:
    url: "http://{{ inventory_hostname }}:{{ vault_port }}/v1/sys/health"
    status_code: 200,400,429,472,501,503
  register: vault_health_response

- name: Is using HTTPS
  set_fact:
    is_https: vault_health_response.status == 400 | bool

- name: Display the health data
  debug:
    msg: "{{ vault_health_response }}"

- name: Setting fact boolean value
  debug:
    msg: "{{ is_https }}"
# #Downside of this is only checking and individual Vault host
# - name: Check if using HTTPS
#   lineinfile:
#     path: "{{ base_vault_dir }}/{{ vault_containers[0].key }}/vault/config/vault.hcl"
#     regexp: '^(\s*)tls_cert_file\s(.*?)$'
#     state: absent
#   check_mode: yes
#   changed_when: false
#   register: is_https

# - name: Wait for service to be ready
#   wait_for:
#     port: 8200
#     host: 127.0.0.1
#     connect_timeout: 3
#     delay: 3
#     timeout: 30
