---
tls_skip_verify: true

vault_root_token_file: ~/vault/root-token.txt
vault_root_token: "{{ lookup('file', '~/vault/root-token.txt', errors='ignore') }}" #if already initialised root token may exist in file so read it in so that audit check can be done
