---

- name: Set the vault config to use TLS
  lineinfile:
    dest: "{{ config_file}}"
    regexp: "{{ config_text.regexp }}"
    line: "{{ config_text.line }}"
    backrefs: true
  loop:
    - { regexp: '^#tls_cert_file\s(.*?)$', line: 'tls_cert_file  \1' }
    - { regexp: '^#tls_key_file\s(.*?)$', line: 'tls_key_file  \1' }
    - { regexp: '^tls_disable(\s*=\s*).*?$', line: 'tls_disable\1"false"' }
  loop_control:
    loop_var: config_text