---

- name: Update consul server TLS configuration
  include_tasks: enable-tls-consul.yml
  vars:
    config_file: "{{ base_consul_dir }}/{{ server }}/config/consul.hcl"
  register: consul_config_result
  loop: "{{ consul_servers }}"
  loop_control:
    loop_var: server

- name: Update the vault consul client TLS configuration
  include_tasks: enable-tls-consul.yml
  vars:
    config_file: "{{ base_vault_dir }}/{{ item.key }}/consul/config/consul.hcl"
  with_dict: "{{ vault_servers }}"
  #notify: Restart Consul #even though in a loop, will only result in one restart

- name: Update the vault TLS configuration
  include_tasks: enable-tls-vault.yml
  vars:
    config_file: "{{ base_vault_dir }}/{{ item.key }}/vault/config/vault.hcl"
  register: vault_config_result 
  with_dict: "{{ vault_servers }}"

- name: Display the consul results
  ansible.builtin.debug:
    msg: "{{ consul_config_result }}"

- name: Display the vault results
  ansible.builtin.debug:
    msg: "{{ vault_config_result }}"

#TODO: Restart when condition below is not working using registered loop var

- name: (Re)start consul docker containers all
  include_role:
    name: consul-container-restart-all
  # when:
  #   - consul_key_added is defined and consul_key_added.changed

- name: (Re)start vault docker containers
  include_role:
    name: vault-container-restart-all
  # when:
  #   - vault_consul_key_added is defined and vault_consul_key_added.changed